### ISSUE TITLE
Design/layout specs

### ISSUE THREAD

**Issue by elliot-huck** [cohort-26-website-committee/class-website#7]
# Agency template layout

The site's design should follow the general theme of [this template](https://startbootstrap.com/template-overviews/agency/). Other sites to be used for inspiration are the pages for [Cohort 19](https://nss-c19-website.github.io/Class-Page/) and [Cohort 24](https://nss-day-cohort-24.github.io/Class-Site/).

### Design notes (design team)

Sections should be included in the following order from top to bottom.

* [ ] Nav bar ( issue ticket #5 )
* [ ] Cohort picture ( issue ticket #2 )
* [ ] Technologies scroll bar ( issue ticket #4 )
* [ ] Student info ( issue ticket #1 )
* [ ] Special Thanks ( issue ticket #6 )

Check in periodically with the Design team as necessary to answer questions and keep them in the loop.
